config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
  resources :listings
 
  
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/gallery' => 'pages#gallery'
  get '/listings' => 'listings#index'
  
  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
      delete "remove", path: "destroy/:id"
      get :checkout
  end
  
  resources :orders, only: [:index, :show, :create]
  
  resources :contacts, only: [:new, :create]

  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "150x150>", thumb: "50x30>" }, default_url: "sorrynoimage-200x200.jpg",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => ":style/:id_:filename"
                
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    validates :name, :description, :price, presence: true
    validates :price, numericality: {greater_than: 0}
  
    
    belongs_to :category
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :initialize_cart
  before_action :authenticate_admin!, only: [:new, :edit, :update, :create, :destroy]
 
  

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.page(params[:page] || 1).per(params[:per_page] || 9).all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image, :category_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for(@listing, :html => {:multipart => true }) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "Please select.."}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div><br>
<% end %>

app/views/listings/_list.html.erb
<% if current_user && current_user.admin? %>
  <%= link_to 'New Listing', new_listing_path %>
<% end %>
<div class="center">
  <div class="row">
    <% listings.each do |listing| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= image_tag listing.image.url %>
          <div class="caption">
            <h4><%= listing.name %></h4>
            <p><%= number_to_currency(listing.price, :unit => "€") %></p><br>
            <%= link_to 'Show', listing, class: "btn btn-primary" %>
            <% if current_user && current_user.admin? %>
              <%= link_to 'Edit', edit_listing_path(listing) %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div> 
  
</div>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h2> Products for Sale </h2>
<%= paginate @listings, theme: "twitter-bootstrap-3" %>
<%= render "listings/list", listings: @listings %>





  

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url(:medium) %>
    </div>
  </div>
  <div class="col-md-8">
      <h3><%= link_to @listing.category.name, @listing.category %></h3>
      <h3><%= @listing.name %></h3><hr>
      <p><%= @listing.description %></p><hr>
      <p><%= number_to_currency(@listing.price, :unit => "€") %></p>
  </div><br>
  
</div>
<div class="col-md-4"></div>
<div class="col-md-8">

<%= link_to "Add to cart", add_cart_path, method: :post, class: "btn btn-primary" %> 
<%= link_to 'Back to products', listings_path, class: "btn btn-default" %>

<% if current_user && current_user.admin? %>
  <%= link_to 'Edit product', edit_listing_path(@listing), class: "btn btn-default" %> 
<% end %>
</div>