config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
  resources :listings
 
  
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/gallery' => 'pages#gallery'
  get '/listings' => 'listings#index'
  
  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
      delete "remove", path: "destroy/:id"
      get :checkout
  end
  
  resources :orders, only: [:index, :show, :create]
  
  resources :contacts, only: [:new, :create]

  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/cart.rb
class Cart
  attr_reader :items

   def self.build_from_hash hash
    items = if hash["cart"] then
       hash["cart"]["items"].map do |item_data|
     CartItem.new item_data["listing_id"], item_data["quantity"]
    end
    else
      []
    end
    new items
   end 

  def initialize items = []
    @items = items
  end

  def add_item listing_id
   item = @items.find {|item| item.listing_id == listing_id}
     if item
       item.increment
     else
       @items << CartItem.new(listing_id)
     end
  end

   def empty?
     @items.empty?
   end

   def count
     @items.length
   end

    def serialize
      @items = @items.map do |item|

      {
         "listing_id" => item.listing_id,
         "quantity" => item.quantity
      }
      end
      {
       
      "items" => items

      }
    end
    
    def total_price
        @items.inject(0) { |sum, item| sum + item.total_price }
    end
  
    
   
   
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
   before_filter :initialize_cart
   before_action :authenticate_user!, only: [:add]
   
   def add
     @cart.add_item params[:id]
     session["cart"] = @cart.serialize
     listing = Listing.find params[:id]
     redirect_to :back, notice: "Added #{listing.name} to cart."
   end
   
   def show
   end
   def remove
      cart = session['cart']
      item = cart['items'].find {|item| item['listing_id'] == params[:id]}
      if item
         cart['items'].delete item
      end
      redirect_to cart_path
      
   end
   
   def checkout
      @order_form = OrderForm.new user: User.new
   end
   

 
    
end

app/views/carts/checkout.html.erb
<h2>Checkout</h2>
<div class="center">
    <% if user_signed_in? %>
        <h3>Hi, <%=  current_user.email  %></h3>
    <% end  %>
        <h3>You are checking out following products</h3>
</div>
<br>
<div class="row">
    <div class="col-md-4">
        <table class="table table-condensed">
            <tr>
                <th>Quantity</th>
                <th>Product name</th>
                <th>Total price</th>
            </tr>
            <ul>
                <% @cart.items.each do |item| %>
                    <tr>
                        
                        <td><%= item.quantity %></td>
                        <td><%= link_to item.listing.name, item.listing %></td>
                        <td class="text-right"><%= number_to_currency(item.total_price, :unit => "€") %></td>
                    </tr>
                <% end %>
            </ul>
            <tfoot>
                <td></td>
                <td class="text-right"><strong>  Total price for items: </strong></td>
                <td><%= number_to_currency(@cart.total_price, :unit => "€") %></td>
            </tfoot>
        </table>
    </div>
        <div class="col-md-8">
            <%= form_for @order_form, url: orders_path do |f| %>
                <%= fields_for :user, @order_form.user do |u|  %>
                    <p><%= u.text_field :name, placeholder: "Your Name", class: "form-control input-lg" %></p>
                    <p><%= u.text_field :email, placeholder: "Your Email Address", class: "form-control input-lg" %></p>
                    <div class="row">
                        <p class="col-md-12"><%= u.text_field :address, placeholder: "Your Address", class: "form-control input-lg" %></p>
                        <p class="col-md-8"><%= u.text_field :city, placeholder: "Your City", class: "form-control input-lg" %></p>
                        <p class="col-md-4"><%= u.text_field :name, placeholder: "Your Postal Code", class: "form-control input-lg" %></p>
                        <p class="col-md-12"><%= u.country_select :country, {priority_countries: ["ie", "gb", "pl"]}, {class: "form-control"} %></p>
                        <p class="col-md-12"><%= u.text_field :phone, placeholder: "Your Phone Number", class: "form-control input-lg" %></p>
                    </div>
                <% end %>
                <p><%= f.submit "Place Your Order", class: "btn btn-primary" %></p>
            <% end %>
            
        
        
        
        </div>
</div>

app/views/carts/show.html.erb
<table class="table table-hover table-bordered table-striped">
 
    <tr>
        <th>Image</th>
        <th>Quantity</th>
        <th>Product name</th>
        <th>Total price</th>
        <th>Remove product</th>
    </tr>
    <% @cart.items.each do |item| %>
          <tr>
            <td class="thumbnail"><%= image_tag item.listing.image.url(:thumb) %></td> 
            <td><%= item.quantity %></td>
            <td><%= link_to item.listing.name, item.listing %></td>
            <td class="text-right"><%= number_to_currency(item.total_price, :unit => "€") %></td>
            <td><%= link_to "remove item", remove_cart_path(item.listing_id), :method => :delete, :confirm => "Are you sure?",:remote => true %></td>
         </tr>    
    <% end %>
<tfoot>
    <tr>
        <td></td>
        <td></td>
        <td class="text-right">
            <strong>  Total price for items: </strong>
        </td>
        <td class="text-right">
            <strong><%= number_to_currency(@cart.total_price, :unit => "€") %></strong>
        </td>
    </tr>
 </tfoot> 
</table>
<p><%= link_to 'Checkout', checkout_cart_path, class: "btn btn-primary" %></p>