config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  devise_for :users
  resources :listings
 
  
  get '/home' => 'pages#home'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'
  get '/gallery' => 'pages#gallery'
  get '/listings' => 'listings#index'
  
  resource :cart, only: [ :show ] do
    post "add", path: "add/:id"
      delete "remove", path: "destroy/:id"
      get :checkout
  end
  
  resources :orders, only: [:index, :show, :create]
  
  resources :contacts, only: [:new, :create]

  root 'pages#home'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_cart.html.erb
<% if @cart %>
    <p class="navbar-text navbar-right">
        <% if @cart.empty? %>
            Cart (0) Your cart is empty
        <% else %>
            <%= link_to "You have #{pluralize @cart.count, "item"}.", cart_path %>
        <% end %>
    </p>
<% end %>

app/views/layouts/_footer.html.erb
	<div id="footer">
	 <h6 class="footertext">&copy;  Sandcourt beach & soccer club; 2016</h6>
	</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="logo" href="/listings" >Sandcourt</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Contact", new_contact_path %></li>
        <li><%= link_to "Rental", contact_path %></li>
        
        
        <!--<li class="active"><a href="/about">About <span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="/contact">Contact <span class="sr-only">(current)</span></a></li>
        <li class="active"><a href="/gallery">Gallery <span class="sr-only">(current)</span></a></li>-->
   
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to 'All', root_path %>
            </li>
                  <% @categories.each do |category| %>
                    <li>
                      <%= link_to category.name, category %>
                    </li>
                  <% end %>
          </ul>
        </li>
      </ul>
      
      
 
      
    	<ul class="nav navbar-nav navbar-right">
    	  <% if current_user && current_user.admin? %>
    	   <li><%= link_to "Dashboard", new_admin_user_session_path %></li>
    	   <% end %>
    	   <% if user_signed_in? %>
    	   <li><%= link_to current_user.email, edit_user_registration_path  %></li>
    	   <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
    	  
    		 <li><%= render "layouts/cart" %></li>
    	</ul>
    	 <% else %>
         <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>  
  	  </ul>
   

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artvballecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://maps.google.com/maps/api/js?sensor=true" type="text/javascript"></script>
  <!-- This stylesheet contains specific styles for displaying the map
         on this page. Replace it with your own styles as described in the
         documentation:
         https://developers.google.com/maps/documentation/javascript/tutorial -->
  <meta name="viewport" content="initial-scale=1.0">
  <meta charset="utf-8">
</head>
<body>
  
    <%= render 'layouts/nav' %>
    
    <div class="container">
      
      <% flash.each do |name, msg|  %>
        <% if msg.is_a?(String) %>
          <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
            <button type="buton" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
          </div>
        <% end %>
      <% end %>
        <!--<p><%= content_tag :div, notice, class: "bg-success" %></p>-->
        <!--<p><%= content_tag :div, alert, class: "bg-danger" %>-->
      <%= yield %>
    
     
   </div>
   
   <%= render 'layouts/footer' %>
</body>
</html>